defmodule Registratie.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Users table already created in earlier migration; nothing to do.
  end

  def down do
    :ok
  end
end
